Add technical criteria
goatcorp/DalamudPluginsD17 pull request #681
Opened 2022-10-30 23:18 UTC by goaaats

2022-10-30 23:50 UTC, philpax requested changes
I'd like to add this section afterwards:

```markdown
### Approval criteria

When the plugin approval group checks your plugin, they will check for the following:

- Does it meet [our guidelines](https://goatcorp.github.io/faq/development#q-what-am-i-allowed-to-do-in-my-plugin), as agreed upon by multiple members of the group?
- Does it feature any combat elements? If so, are they purely informational, and show only information the player would normally know?
- Does it pass an informal code review?
- Does it install cleanly?
- Does the configuration window behave correctly?
- Does the base functionality of the plugin work (if testable easily)?
- Does it have no obvious technical issues?
- Is its JSON correctly formatted? (We hope to [make this unnecessary in future](https://github.com/goatcorp/DalamudPackager/issues/8))
- If it's a new plugin, is it in the testing channel and not the stable channel?
- Does it meet the [Technical criteria](#technical-criteria)?

These criteria are intended to prevent issues for users. We're happy to work with you to get you across the line; just reach out in the Discord.
```

Are you okay with that?

2022-11-02 12:41 UTC, philpax commented
ping @goaaats

2022-11-07 00:56 UTC, goaaats reviewed
add phil's stuff

2022-11-07 16:31 UTC, philpax approved these changes

2022-11-07 16:31 UTC, merged